// Lista completa de conversii identificate pe HomePitch.ro
// Bazata pe analiza paginilor si evenimentelor GA4

export const CONV_DEFINITIONS = [
  // ── INREGISTRARE / ONBOARDING ──────────────────────────────────────
  {
    id: 'conversions_bun_venit_cumparator',
    label: 'Inregistrare cumparator',
    description: 'User nou inregistrat ca si cumparator (viziteaza /bun-venit-cumparator)',
    category: 'Inregistrare',
    page: '/bun-venit-cumparator',
    value: 5,
    icon: '👤',
    defaultOn: true,
  },
  {
    id: 'conversions_bun_venit_agent',
    label: 'Inregistrare agent',
    description: 'Agent nou inregistrat pe platforma (viziteaza /bun-venit-agent)',
    category: 'Inregistrare',
    page: null,
    value: 15,
    icon: '🏢',
    defaultOn: true,
  },
  {
    id: 'conversions_bun_venit_proprietar',
    label: 'Inregistrare proprietar',
    description: 'Proprietar nou inregistrat (viziteaza /bun-venit-proprietar)',
    category: 'Inregistrare',
    page: '/bun-venit-proprietar',
    value: 10,
    icon: '🏠',
    defaultOn: true,
  },
  {
    id: 'conversions_signup',
    label: 'Sign-up generic',
    description: 'Orice tip de inregistrare (event conversions_signup)',
    category: 'Inregistrare',
    page: '/login',
    value: 5,
    icon: '✅',
    defaultOn: true,
  },

  // ── CERERI ────────────────────────────────────────────────────────
  {
    id: 'conversions_bravo_cerere_noua',
    label: 'Cerere noua adaugata',
    description: 'Cumparator a adaugat o cerere noua de proprietate',
    category: 'Cereri',
    page: '/cerere-noua',
    value: 20,
    icon: '📋',
    defaultOn: true,
  },
  {
    id: 'cerere_noua_page',
    label: 'Vizita /cerere-noua',
    description: 'User a deschis formularul de cerere noua (intent puternic)',
    category: 'Cereri',
    page: '/cerere-noua',
    value: 8,
    icon: '📝',
    defaultOn: true,
    isPageView: true,
  },

  // ── OFERTE ────────────────────────────────────────────────────────
  {
    id: 'conversions_offer_accepted',
    label: 'Oferta acceptata',
    description: 'O oferta trimisa de agent a fost acceptata de cumparator',
    category: 'Oferte',
    page: '/dashboard/oferte',
    value: 50,
    icon: '🤝',
    defaultOn: true,
  },
  {
    id: 'offer_sent',
    label: 'Vizita /dashboard/oferte-trimise',
    description: 'Agent a vizualizat ofertele trimise (proxy pentru oferta trimisa)',
    category: 'Oferte',
    page: '/dashboard/oferte-trimise',
    value: 5,
    icon: '📤',
    defaultOn: false,
    isPageView: true,
  },

  // ── ENGAGEMENT PROPRIETATI ────────────────────────────────────────
  {
    id: 'proprietate_noua',
    label: 'Proprietate noua adaugata',
    description: 'Agent sau proprietar a adaugat o proprietate (/proprietati/nou)',
    category: 'Proprietati',
    page: '/proprietati/nou',
    value: 25,
    icon: '🏗️',
    defaultOn: true,
    isPageView: true,
  },
  {
    id: 'open_house',
    label: 'Open House vizitat',
    description: 'User a vizitat pagina Open House — interes activ',
    category: 'Proprietati',
    page: '/open-house',
    value: 10,
    icon: '🚪',
    defaultOn: false,
    isPageView: true,
  },

  // ── ENGAGEMENT CUMPARATOR ─────────────────────────────────────────
  {
    id: 'scor_cumparator',
    label: 'Scor cumparator vizitat',
    description: 'User a verificat scorul sau de cumparator — engagement ridicat',
    category: 'Engagement',
    page: '/scor-cumparator',
    value: 8,
    icon: '⭐',
    defaultOn: false,
    isPageView: true,
  },
  {
    id: 'recomandari_ai',
    label: 'Recomandari AI vizualizate',
    description: 'User a deschis sectiunea de recomandari AI din dashboard',
    category: 'Engagement',
    page: '/dashboard/recomandari',
    value: 5,
    icon: '🤖',
    defaultOn: false,
    isPageView: true,
  },
  {
    id: 'vreau_page',
    label: 'Vizita /vreau',
    description: 'Pagina de interes activ pentru cumparare',
    category: 'Engagement',
    page: '/vreau',
    value: 3,
    icon: '🎯',
    defaultOn: false,
    isPageView: true,
  },

  // ── ACTIVARE CRM ──────────────────────────────────────────────────
  {
    id: 'setari_crm',
    label: 'Setari CRM accesate',
    description: 'Agent a accesat setarile CRM — user activ cu intentie de utilizare',
    category: 'CRM',
    page: '/setari-crm',
    value: 10,
    icon: '⚙️',
    defaultOn: false,
    isPageView: true,
  },
  {
    id: 'preturi_page',
    label: 'Vizita /preturi',
    description: 'User interesat de planuri platite — lead calificat',
    category: 'Monetizare',
    page: '/preturi',
    value: 15,
    icon: '💰',
    defaultOn: true,
    isPageView: true,
  },
]

export const CATEGORIES = [...new Set(CONV_DEFINITIONS.map(c => c.category))]
